### PR TITLE
feat: add user timelines missing fields

### PR DESCRIPTION
**Pull request by redouane59**
fixing https://github.com/redouane59/twittered/issues/340

### CODE REVIEW

**Comment by jormungander** [comment]
I think ALL_EXPANSIONS needs to include geo.place_id in order for the places to get added to the includes structure.

**Comment by redouane59** [comment]
Hey @jormungander . Really ? Add it to `ALL_PLACE_FIELDS` is not enough ?

**Comment by jormungander** [comment]
Yes.  The ALL_PLACE_FIELDS in place.fields tells it which fields to include, but it's the presence of the geo.place_id in expansions which tells Twitter's API whether to put those fields in the includes or not, basically an on/off switch.  I've verified this with the API collection Twitter provides for Postman.

**Comment by redouane59** [comment]
https://github.com/redouane59/twittered/pull/352

**Comment by redouane59** [comment]
Thanks, it is fixed and will be available on the next release : https://github.com/redouane59/twittered/pull/352

**Comment by jormungander** [comment]
I just got around to checking this and I see there's more to it.  The Includes class that the TweetList uses (which comes from TweetV2) does not contain a List to put the places data that it's receiving.

**Comment by redouane59** [comment]
Could you please submit a pull request @jormungander ?

**Pull request merged**
