### PR TITLE
Resolves #344 "Wrong FilteredStreamRulePredicate#and(FilteredStreamRulePredicate) implementation"

### LINKED ISSUE #344: Wrong FilteredStreamRulePredicate#and(FilteredStreamRulePredicate) implementation
`And` operator in the Twitter query syntax looks like a single space `" "`, not `" AND "`. 
`" AND "` is interpreted as "filter tweets containing `AND` keyword"

See [Boolean operators and grouping](https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query#boolean) section.
Also see a [warning here](https://developer.twitter.com/apitools/query?query=a2V5d29yZEEgQU5EIGtleXdvcmRC):
> An uppercase 'AND' will be interpreted as a keyword. For AND logic, use a single whitespace ' ' between clauses

### PR DESCRIPTION
**Pull request by rzo1**
as the title says

### CODE REVIEW

**Comment by redouane59** [comment]
Please also fix your unit tests :)

**Comment by rzo1** [comment]
> Please also fix your unit tests :)

You are too fast for me ;)

**Comment by rzo1** [comment]
Fixed now.

**Comment by redouane59** [comment]
Haha thanks !

**Pull request merged**
