### PR TITLE
v2.5

### PR DESCRIPTION
**Pull request by redouane59**
- Fixing some log messages : https://github.com/redouane59/twittered/pull/241/
- Fixing `User` and `Twitter` object serialization : https://github.com/redouane59/twittered/pull/244
- Fixing `searchAllTweets` method https://github.com/redouane59/twittered/pull/255
- Global code reformatting 
- Setting v1 search method as `Deprecated` and removing the old `getFavorites()` method

### CODE REVIEW

**Comment by calves07** [comment]
ETA on this release?

**Comment by redouane59** [comment]
> ETA on this release?

I will try to release it next week-end as a maximum, stay tuned :)

**Comment by calves07** [comment]
> > ETA on this release?
> 
> I will try to release it next week-end as a maximum, stay tuned :)

Anyway I can easily use this version before the official release?

**Comment by redouane59** [comment]
> Anyway I can easily use this version before the official release?

Yes I guess that you can just fork and build it locally

**Comment by calves07** [comment]
I forked the project as suggested but I wasn't able to serialize the objects.
I had to add ``implements Serializable`` in classes UserV2, UserData and UserPublicMetrics. Now yes, I can serialize objects.

**Comment by redouane59** [comment]
> I had to add `implements Serializable` in classes UserV2, UserData and UserPublicMetrics. Now yes, I can serialize objects.

That's not normal. Can you just launch the unit test `testSerialization()` in `UserDeserializerV2Test.java` and tell me if it passes ? Because on my side it is.

**Comment by calves07** [comment]
The test did pass, yes, but in my own project it still failed to serialize with
````
FileOutputStream fileOut = new FileOutputStream(file);
ObjectOutputStream out = new ObjectOutputStream(fileOut);
out.writeObject(object);
out.close();
fileOut.close();
````
After implementing Serializable, there are no longer exceptions and it works fine.

**Comment by redouane59** [comment]
> After implementing Serializable, there are no longer exceptions and it works fine.

Are you sure your project is using this new version ?

**Comment by calves07** [comment]
Yes.

De: Redouane ***@***.***>
Enviado: 5 de julho de 2021 14:19
Para: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Assunto: Re: [redouane59/twittered] v2.5 (#242)


After implementing Serializable, there are no longer exceptions and it works fine.

Are you sure your project is using this new version ?

**Comment by redouane59** [comment]
Can you please write to me here your full test please ?

**Comment by calves07** [comment]
Just get a random UserV2 or User or UserData object.

Then call this function:

````
public static boolean serialize(Object object, String file) {
        try {
            FileOutputStream fileOut = new FileOutputStream(new File(file));
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(object);
            out.close();
            fileOut.close();
        } catch (Exception ex) {
            return false;
        }
        return true;
    }
````
In my tests with a similar function, NotSerializableException was thrown.

**Comment by redouane59** [comment]
Thank you very much, I'm currently debugging that :)

**Comment by redouane59** [comment]
I just merge the PR https://github.com/redouane59/twittered/pull/249 .
Could you just try this : 
```
  @Test
  public void getAndSerializeUser() throws IOException {
    String userName = "RedouaneBali";
    User   result   = twitterClient.getUserFromUserName(userName);
    assertNotNull(TwitterClient.OBJECT_MAPPER.writeValueAsString(result));
    TwitterClient.OBJECT_MAPPER.writeValue(new File("../test_serialization.json"), result);
  }
```

**Pull request merged**
