### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by NyCodeGHG**
this PR updates all dependencies to their latest version.

Also i noticed i can't build the project in IntelliJ IDEA without removing
```xml
<plugin>
  <artifactId>sonar-maven-plugin</artifactId>
  <groupId>org.codehaus.sonar</groupId>
  <version>3.8.0.2131</version>
</plugin>
```
do i have to configure something?

### CODE REVIEW

**Comment by redouane59** [comment]
> do i have to configure something?

Really strange, on my side it was building correctly. I'm currently out of my home but I'll try to check it as soon as possible.

**Comment by NyCodeGHG** [comment]
when i run `mvn package` it works fine, but i can't build in intellij

**Comment by redouane59** [comment]
Really strange. I didn't remember to have faced this problem, I'm also using Intellij. What is the error you have ?

**Comment by NyCodeGHG** [comment]
```
[WARNING] The POM for org.codehaus.sonar:sonar-maven-plugin:jar:3.8.0.2131 is missing, no dependency information available
Cannot resolve plugin org.codehaus.sonar:sonar-maven-plugin:3.8.0.2131
```

**Comment by redouane59** [comment]
Ok actually I'm having the same issue.

**Pull request merged**
