### PR TITLE
Switches codebase to ASL 2.0 license

### PR DESCRIPTION
**Pull request by rzo1**
# What does this PR do?

- Switches codebase to ASL 2.0 license

### CODE REVIEW

**Comment by redouane59** [comment]
Is it mandatory to add on each file the big header of comments ?

**Comment by rzo1** [comment]
> Is it mandatory to add on each file the big header of comments ?

Yup (afaik it would be the same for the GPL ...)

**Comment by redouane59** [comment]
Just found that [there](https://softwareengineering.stackexchange.com/questions/125836/do-you-have-to-include-a-license-notice-with-every-source-file)

```
In short, you don't need to put the license in each file. I think it's overkill. There's no extra legal protection in doing so. It does help a downstream user somewhat, but not by much.

I think the tradition of lots of comment-based metadata (license, creation date of each function, changelog, etc.) are very old traditions which exist because they are easy to do and which more a talisman than useful.
``` 

Just to keep file lighter I would prefer to add so much lines :) 

Thanks !

**Comment by rzo1** [comment]
No problem. Changed it :)

**Comment by redouane59** [comment]
Perfect thanks. I'm going to release the version 2.7 tonight.

**Pull request merged**
