### PR TITLE
v2.16

### PR DESCRIPTION
**Pull request by redouane59**
- https://github.com/redouane59/twittered/pull/354 : adding get list members endpoint
- https://github.com/redouane59/twittered/pull/357 : adding places to Tweet includes

### CODE REVIEW

**Comment by Yicong-Huang** [comment]
Hi @redouane59, any plan for the release of v2.16?

**Comment by RedouaneBALI** [comment]
> Hi @redouane59, any plan for the release of v2.16?

Hey, sorry I've been a lot busy these last few weeks. I'll try to deploy it this week-end.

**Comment by redouane59** [comment]
Done :)

**Comment by Yicong-Huang** [comment]
> Done :)
Thanks a lot!

**Pull request merged**
