### PR TITLE
v2.13

### PR DESCRIPTION
**Pull request by redouane59**
- https://github.com/redouane59/twittered/pull/328
- https://github.com/redouane59/twittered/pull/324
- https://github.com/redouane59/twittered/pull/331
- https://github.com/redouane59/twittered/pull/334

### CODE REVIEW

**Comment by steebchen** [comment]
I'd appreciate if this would get merged soon, otherwise the OAuth flow is broken. Thanks for fixing this though!

**Comment by redouane59** [comment]
> I'd appreciate if this would get merged and published soon, otherwise the OAuth flow is broken because of #328. Thanks for fixing this though!

Hey @steebchen , I would like to wait for @PhantomYdn to solve https://github.com/redouane59/twittered/issues/326 before releasing this new version. But if during this week-end he doesn't have time to implement it, I will release this version without this feature.

**Comment by steebchen** [comment]
Maybe would make more sense to release now with the fix and then put #326 into the next version. That's just my 2 cents though, don't want to infere too much with your planning. I'd just appreciate if I can upgrade to the newer version to the bugfix for oauth :)

**Comment by redouane59** [comment]
> Maybe would make more sense to release now with the fix and then put #326 into the next version. That's just my 2 cents though, don't want to infere too much with your planning. I'd just appreciate if I can upgrade to the newer version to the bugfix for oauth :)

Done :)

**Comment by steebchen** [comment]
Thanks so much! This helps us a lot in our project :)

**Comment by redouane59** [comment]
You're welcome !

**Pull request merged**
